# Users
login_attempts_history_length: 10
login_attempts_check_minutes: 10
next_login_seconds_per_attempt: 5
password_reset_token_bytes: 64 # 512 bits
min_password_bits: 70
bcrypt_rounds: 12

# Session
session_token_bytes: 64 # 512 bits
session_expire_seconds: 300

# Notes
max_note_lines: 50
max_note_length: 4000
max_note_title_length: 100
max_note_readers_length: 500
